### PR TITLE
404 when requesting page nonexistent-exhibit

### LINKED ISSUE #1270: Return a 404 when a page is requested on a nonexistent exhibit
url to replicate this error: https://dpul.princeton.edu/not_an_exhibit/about/about
working url: https://dpul.princeton.edu/eastasian/about/about

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/82551778)

This is not the same as #1200. It is probably the same as #849 which was closed as a duplicate of #1200 but I don't think was a duplicate.

### PR DESCRIPTION
**Pull request by XanderGardner**
closes #1270

### CODE REVIEW

**Review by hackartisan — CHANGES_REQUESTED** [review]
If we respond to all NoMethodErrors with 404s at this global ApplicationController level I expect we will hide a lot of valid 500 responses that we want to see come through honeybadger. 404 is also not a valid code for most NoMethodErrors.

The test and the fix should likely be targeted more closely to the pages controller.

File: config/initializers/monkeypatches/nonexistent_exhibit_patch.rb [hunk 1]
```diff
@@ -0,0 +1,17 @@
+# frozen_string_literal: true
+
+Rails.application.config.to_prepare do
```
Comment (hackartisan) [inline config/initializers/monkeypatches/nonexistent_exhibit_patch.rb:3]: We should add a link to the upstream code for future reference. I'll go ahead and commit it to this PR.

**Review by hackartisan — APPROVED** [review]
This looks great. Thank you @XanderGardner!
