### PR TITLE
Fix show presenter

### LINKED ISSUE #954: Update RTL Show Presenter for Spotlight 3

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #954

### CODE REVIEW

File: spec/models/iiif_resource_spec.rb [hunk 1]
```diff
@@ -301,165 +301,166 @@
...
-          :get,
-          url
-        ).to_return(body: JSON.generate(collections_manifest))
-        stub_request(
-          :head,
-          url
-        ).to_return(headers: { 'Content-Type' => 'application/json; charset=utf-8' })
-      end
-    end
+    # TODO: Add tests
```
Comment (tpendragon) [inline spec/models/iiif_resource_spec.rb:304]: Question: Why's all this commented?

Comment (eliotjordan) [reply spec/models/iiif_resource_spec.rb:304]: There's no test in that context and rubocop is complaining. I wasn't sure if the test was removed during this process with the idea that it needed to be put back eventually.

Comment (tpendragon) [reply spec/models/iiif_resource_spec.rb:304]: Oh yeah, it was all set up to test that a pretty error happened when there was a bad collection metadata hash.  I ripped it out because it was a lot of code to just error a little differently. https://github.com/pulibrary/dpul/blob/main/spec/models/iiif_resource_spec.rb#L469 was the test. I think we can just delete this whole block.

Comment (eliotjordan) [reply spec/models/iiif_resource_spec.rb]: Done.

File: app/presenters/rtl_show_presenter.rb [hunk 2]
```diff
@@ -75,7 +75,11 @@ def override_title_field
   end
 
   def html_title
-    super.split("<br />").map(&:html_safe).join(", ").gsub(/<.*?>/, "")
+    # Insert field_value_separator between tags
+    value = super.gsub("li><li", "li>#{field_value_separator}<li")
```
Comment (hackartisan) [inline app/presenters/rtl_show_presenter.rb:79]: Maybe we can split on the full tag like
`value.split("</li><li>").map(&:html_safe).join(", ").gsub(/<.*?>/, "")`

**Review by hackartisan — COMMENTED** [review]
So I think this means we need a ticket for updating all the Blacklight::Configurations to add `link_to_facet` where they have `link_to_search`, yes?

**Review by hackartisan — APPROVED** [review]
